
[env]
TERM                   = "screen-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 18

normal.family = "AnonymicePro Nerd Font Mono"

offset.x = 1
offset.y = 1 

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations               = "Buttonless"
decorations_theme_variant = "Dark"
dynamic_padding           = false
opacity                   = 1
startup_mode              = "Windowed"
title                     = ""
padding.x                 = 2
padding.y                 = 0

[window.class]
general  = "Alacritty"
instance = "Alacritty"

# Mellifluous
[colors.primary]
foreground = '#dddddd'
background = '#1d1d1d'

[colors.cursor]
text = '#1d1d1d'
cursor = '#dddddd'

[colors.normal]
black = '#1d1d1d'
red = '#d0a08a'
green = '#accca4'
magenta = '#bf9ac1'
white = '#dddddd'

[colors.bright]
black = '#777777'
red = '#d0a08a'
green = '#bccda1'
magenta = '#bc9ead'
white = '#ffffff'
