[general]
import = [
    "./themes/themes/umbraline.toml",
]

[env]
TERM                   = "screen-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 18

normal.family = "Terminess Nerd Font Mono"

offset.x = 1
offset.y = 1 

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations               = "Buttonless"
decorations_theme_variant = "Dark"
dynamic_padding           = false
opacity                   = 0.85
startup_mode              = "Windowed"
title                     = ""
padding.x                 = 2
padding.y                 = 0

[window.class]
general  = "Alacritty"
instance = "Alacritty"


