live_config_reload = true

[env]
TERM = "screen-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 15

normal.family = "BlexMono Nerd Font"
normal.style = "Regular"

bold.family = "BlexMono Nerd Font"
bold.style = "Bold"

bold_italic.family = "BlexMono Nerd Font"
bold_italic.style = "Bold Italic"

italic.family = "BlexMono Nerd Font"
italic.style = "Italic"


[mouse]
hide_when_typing = true

[shell]
program = "/bin/zsh"

[window]
decorations = "Buttonless"
decorations_theme_variant = "Dark"
dynamic_padding = false
opacity = 0.95
startup_mode = "Windowed"
title = ""
padding.x = 2
padding.y = 2

[window.class]
general = "Alacritty"
instance = "Alacritty"

### Colors ###
# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'
