
[env]
TERM                   = "screen-256color"
WINIT_X11_SCALE_FACTOR = "1.25"

[font]
size = 18

normal.family = "AnonymicePro Nerd Font Mono"

offset.x = 1
offset.y = 1 

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"

[window]
decorations               = "Buttonless"
decorations_theme_variant = "Dark"
dynamic_padding           = false
opacity                   = 1
startup_mode              = "Windowed"
title                     = ""
padding.x                 = 2
padding.y                 = 0

[window.class]
general  = "Alacritty"
instance = "Alacritty"

# Rasmus
[colors.primary]
background = '#1a1a19'
foreground = '#d1d1d1'

  # Cursor colors
[colors.cursor]
text   = '#1a1a19'
cursor = '#d1d1d1'

  # Normal colors
[colors.normal]
black   = '#333332'
red     = '#ff968c'
green   = '#61957f'
yellow  = '#ffc591'
blue    = '#8db4d4'
magenta = '#de9bc8'
cyan    = '#7bb099'
white   = '#d1d1d1'

  # Bright colors
[colors.bright]
black   = '#4c4c4b'
red     = '#ffafa5'
green   = '#7aae98'
yellow  = '#ffdeaa'
blue    = '#a6cded'
magenta = '#f7b4e1'
cyan    = '#94c9b2'
white   = '#eaeaea'
