#!/bin/bash

set -euo pipefail

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m' # No Color

DOTFILES="$HOME/.mac_config"
OUTPUT=$DOTFILES"/installation/brew_dependencies.txt"

log() {
  echo -e "${GREEN}[INFO]${NC} $1"
}

error() {
  echo -e "${RED}[ERROR]${NC} $1" >&2
  exit 1
}

main() {
  [ -f $OUTPUT ] && log "Removing current dependency file: $OUTPUT" && rm $OUTPUT
  brew bundle dump --file=$OUTPUT || error "Could not save the dependencies."
  log "Dependencies written successfully."
}

main
