format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$c\
$lua\
$java\
$fill\
$cmd_duration\
$line_break\
$character"""

# $fill\
# $cmd_duration\
# $c\
# $lua\
# $java\
# $time\

palette = "colores"

[palettes.colores]
pink = "#EC50D2"
white = "#FFFFFF"
darkblue = "#2492E6"

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[](red)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
vicmd_symbol = "[](bold green)"

# Directory
[directory]
truncation_length = 3
home_symbol = "ﮟ"
style = "bold bright-blue"
read_only = " "
read_only_style = "pink"
truncate_to_repo = false

# git
[git_branch]
symbol = " "
format = "[$symbol$branch ]($style)"

[git_status]
style = "bold yellow"

[git_metrics]
disabled = false
# added_style = "bold blue"
# format = "[+$added]($added_style)/[-$deleted]($deleted_style) "

# languages
[c]
format = "[$symbol$version ]($style)"

[lua]
symbol = " "
format = "[$symbol$version ]($style)"

[java]
symbol = " "
format = "[$symbol$version ](red)"

#time
[time]
time_format = " %I:%M %P"
format = "[$time]($style) "
style = "bold yellow"
disabled = false

[cmd_duration]
format = "[$duration ]($style)"
style = "bold white"

# Disable the package module, hiding it from the prompt completely
[nodejs]
disabled = true
