#!/usr/bin/env bash

# List of potential directories
potential_dirs=(
  ~/kedada
  ~/personal
  ~/.config
  ~/tfg
  ~/firestartr-ia
  ~/firestartr-pro
  ~/firestartr-test
  ~/councilbox
  ~/prefapp
)

# Filter to only existing directories
existing_dirs=()
for dir in "${potential_dirs[@]}"; do
  if [[ -d "$dir" ]]; then
    existing_dirs+=("$dir")
  fi
done

# Only run find if we have existing directories
if [[ ${#existing_dirs[@]} -gt 0 ]]; then
  dirs=$(find -L "${existing_dirs[@]}" -mindepth 1 -maxdepth 1 -type d)
else
  dirs=""
fi

git_projects=$(fd -H -d 2 -E "Library" -t d "^\.git$" "$HOME" | sed "s#/\.git/##g")

selected=$(echo -e "${dirs[*]}\n${git_projects}" | fzf --layout=reverse --preview-window down --preview "eza --color=always -l {}")

if [[ -z "$selected" ]]; then
  exit 0
fi

session_name=$(basename "$selected" | tr '.' '_')
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s "$session_name" -c "$selected"
  exit 0
fi

if ! tmux has-session -t "$session_name" 2&> /dev/null; then
  tmux new-session -ds "$session_name" -c "$selected"
fi

tmux switch-client -t "$session_name"
